services:
  app:
    build: .
    container_name: todo-app
    ports:
      - "8082:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/tododb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: dmsdbs22
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"

  db:
    image: mysql:8
    container_name: todo-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: dmsdbs22
      MYSQL_DATABASE: tododb
    ports:
      - "3308:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
